[package]
name = "tuiman"
description = "A fast TUI to discover, install and manage TUIs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
nucleo-matcher = "0.3"
ratatui = { version = "0.30", default-features = false, features = ["crossterm"] }
tuiman-index = { path = "../tuiman-index" }
ureq = { version = "3", default-features = false, features = ["rustls", "gzip"] }

[lints]
workspace = true
